#!/bin/bash

python_file="jslog.py"
script_dir=$(dirname "$(realpath "$0")")
target_dir="/usr/local/bin"
target_path="$target_dir/jslog"

if [[ ":$PATH:" != *":$script_dir:"* ]]; then
    echo "export PATH=\"$script_dir:\$PATH\"" >> ~/.bashrc
fi

if [[ -f "$script_dir/$python_file" ]]; then
    python3 "$script_dir/$python_file"
else
    echo "El archivo Python no existe en la ruta proporcionada."
fi

if [[ ! -f "$target_path" ]]; then
    sudo mv "$0" "$target_path" && echo "Script movido a $target_dir."
else
fi
